/*
 * Translatable strings file generated by Glade.
 * Add this file to your project's POTFILES.in.
 * DO NOT compile it as part of your application.
 */

gchar *s = N_("bug-buddy");
gchar *s = N_("GNOME bug-buddy");
gchar *s = N_("This will guide you through the \n"
              "GNOME bug submission process");
gchar *s = N_("Contact Information");
gchar *s = N_("Email Address");
gchar *s = N_("Your Name");
gchar *s = N_("Enter your name and email address, so you will be notified when the\n"
              "bug is resolved, or for developers to request more information from you.");
gchar *s = N_("Bug tracking system to use");
gchar *s = N_("GNOME\n"
              "");
gchar *s = N_("System Configuration");
gchar *s = N_("Please verify that this information is correct");
gchar *s = N_("Package");
gchar *s = N_("Version installed");
gchar *s = N_("Report Information");
gchar *s = N_("This is for a...");
gchar *s = N_("New report");
gchar *s = N_("Existing report");
gchar *s = N_("Bug severity");
gchar *s = N_("Version");
gchar *s = N_("Package");
gchar *s = N_("Bug class");
gchar *s = N_("(descriptions)");
gchar *s = N_("Bug number ");
gchar *s = N_("(Existing bugs)");
gchar *s = N_("Short description");
gchar *s = N_("Extra Information");
gchar *s = N_("Full description of the bug:");
gchar *s = N_("How to repeat the bug:");
gchar *s = N_("Nature of the Bug");
gchar *s = N_("What type of bug are you reporting?");
gchar *s = N_("Application crash with crash dialog");
gchar *s = N_("Application crash with core file");
gchar *s = N_("No crash");
gchar *s = N_("Binary");
gchar *s = N_("Process ID");
gchar *s = N_("Core file");
gchar *s = N_("Debugging Information");
gchar *s = N_("Please wait while bug-buddy\n"
              "collects debugging info...");
gchar *s = N_("Action");
gchar *s = N_("Choose the action you wish to take");
gchar *s = N_("Submit bug report");
gchar *s = N_("Send report to your email address *only*");
gchar *s = N_("Do not send bug report anywhere");
gchar *s = N_("Save the report to a file");
gchar *s = N_("Summary");
gchar *s = N_("The GEGL is watching.");
